use crate::{Adapter, BuildCtx, fingerprint, runner};
use arkon_core::{artifact::{Artifact, DeployableKind}, error::Result, runtime::Runtime};
use std::path::PathBuf;

/// Supported Unity platform targets.
#[derive(Debug, Clone, Copy)]
pub enum UnityPlatform {
    Windows64,
    Linux64,
    WebGL,
}

impl UnityPlatform {
    fn build_target(&self) -> &'static str {
        match self {
            Self::Windows64 => "Win64",
            Self::Linux64   => "Linux64",
            Self::WebGL     => "WebGL",
        }
    }
    fn out_subdir(&self) -> &'static str {
        match self {
            Self::Windows64 => "windows",
            Self::Linux64   => "linux",
            Self::WebGL     => "webgl",
        }
    }
}

pub struct UnityAdapter;

impl UnityAdapter {
    fn unity_exe() -> String {
        // Prefer UNITY_PATH env var, then common install locations
        if let Ok(p) = std::env::var("UNITY_PATH") {
            return p;
        }
        #[cfg(target_os = "linux")]
        return "/opt/unity/Editor/Unity".into();
        #[cfg(target_os = "macos")]
        return "/Applications/Unity/Hub/Editor/2022.3.10f1/Unity.app/Contents/MacOS/Unity".into();
        #[cfg(target_os = "windows")]
        return r"C:\Program Files\Unity\Hub\Editor\2022.3.10f1\Editor\Unity.exe".into();
        #[allow(unreachable_code)]
        "unity".into()
    }

    fn build_platform(ctx: &BuildCtx, platform: UnityPlatform) -> Result<PathBuf> {
        let out_dir = ctx.root
            .join("Builds")
            .join(platform.out_subdir());
        std::fs::create_dir_all(&out_dir)?;

        let unity = Self::unity_exe();
        let cmd = format!(
            "{} -batchmode -quit -projectPath {} -buildTarget {} -executeMethod ArkonBuild.Build -outputPath {}",
            unity,
            ctx.root.display(),
            platform.build_target(),
            out_dir.display(),
        );
        runner::run_shell_command(&cmd, &ctx.root, &ctx.env)?;
        Ok(out_dir)
    }
}

impl Adapter for UnityAdapter {
    fn name(&self) -> &str { "unity" }
    fn description(&self) -> &str { "Unity game — builds Windows x64, Linux x64, WebGL" }

    fn build(&self, ctx: &BuildCtx) -> Result<Artifact> {
        // Determine which platforms to build from meta / env
        let platforms = vec![UnityPlatform::Windows64, UnityPlatform::Linux64, UnityPlatform::WebGL];

        let builds_root = ctx.root.join("Builds");
        std::fs::create_dir_all(&builds_root)?;

        for platform in &platforms {
            tracing::info!(platform = platform.build_target(), "building Unity platform");
            Self::build_platform(ctx, *platform)?;
        }

        let (fp, hashes, size) = fingerprint::fingerprint_dir(&builds_root)?;
        let mut art = Artifact::new("unity", builds_root, DeployableKind::GameBuild);
        art.fingerprint = fp;
        art.file_hashes = hashes;
        art.size_bytes = size;
        art.meta.insert("platforms".into(), "windows,linux,webgl".into());
        Ok(art)
    }

    fn output_dir(&self, ctx: &BuildCtx) -> PathBuf {
        ctx.root.join("Builds")
    }

    fn runtime_info(&self) -> Runtime { Runtime::native() }
    fn deployable_type(&self) -> DeployableKind { DeployableKind::GameBuild }

    fn cache_key(&self, ctx: &BuildCtx) -> String {
        fingerprint::cache_key_from_files(
            &ctx.root,
            &["ProjectSettings/ProjectVersion.txt", "Packages/manifest.json"],
        )
    }

    fn pre_build(&self, ctx: &BuildCtx) -> Result<()> {
        // Ensure the ArkonBuild.cs helper script is present in the project
        let editor_dir = ctx.root.join("Assets/Editor");
        let build_script = editor_dir.join("ArkonBuild.cs");
        if !build_script.exists() {
            std::fs::create_dir_all(&editor_dir)?;
            std::fs::write(&build_script, ARKON_BUILD_CS)?;
            tracing::info!("injected Assets/Editor/ArkonBuild.cs into Unity project");
        }
        Ok(())
    }
}

/// Unity editor C# script that ARKON injects to expose a static build method
/// callable from the -executeMethod CLI flag.
const ARKON_BUILD_CS: &str = r#"
// AUTO-GENERATED by ARKON — do not edit manually.
// This file wires up the Unity CLI build pipeline.
using UnityEditor;
using UnityEditor.Build.Reporting;
using System;
using System.IO;

public static class ArkonBuild
{
    public static void Build()
    {
        string outputPath = GetArg("-outputPath") ?? "Builds";
        string targetStr  = GetArg("-buildTarget")  ?? "Win64";

        BuildTarget target = targetStr switch
        {
            "Win64"   => BuildTarget.StandaloneWindows64,
            "Linux64" => BuildTarget.StandaloneLinux64,
            "WebGL"   => BuildTarget.WebGL,
            _         => throw new Exception($"Unknown buildTarget: {targetStr}")
        };

        var opts = new BuildPlayerOptions
        {
            scenes       = GetEnabledScenes(),
            locationPathName = outputPath,
            target       = target,
            options      = BuildOptions.None,
        };

        BuildReport report = BuildPipeline.BuildPlayer(opts);
        if (report.summary.result != BuildResult.Succeeded)
        {
            EditorApplication.Exit(1);
        }
    }

    static string[] GetEnabledScenes()
    {
        var scenes = new System.Collections.Generic.List<string>();
        foreach (var scene in EditorBuildSettings.scenes)
        {
            if (scene.enabled) scenes.Add(scene.path);
        }
        return scenes.ToArray();
    }

    static string GetArg(string name)
    {
        var args = Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
            if (args[i] == name) return args[i + 1];
        return null;
    }
}
"#;
